SELECT DISTINCT ds.ship_id,
       ds.name,
       ds.callsign,
       ds.mmsi,
       ds.imo,
       ds.mid,
       ds.flag_region,
       ds.flag_state,
       dst.mobile_type,
       dst.ship_type,
       ds.location_system_type,
       ds.a,
       ds.b,
       ds.c,
       ds.d